In [2]:
#WEEKEND fist
import pandas as pd

df_food= pd.read_csv('/Users/naroacorettisanchez/Documents/GitHub/DataSS/Deliveries/delivery_demand_ss_1week_scattered.csv')

In [3]:
df_food

,start_time,order_vertical,order_final_status,start_to_pickup_flight_distance_in_meters,pickup_to_delivery_flight_distance_in_meters,courier_delivery_time_in_minutes,customer_delivery_time_in_minutes,pickup_hexagon_id,delivery_hexagon_id,vehicle_type,start_latitude,start_longitude,end_latitude,end_longitude,day
0,2023-09-18 09:31:39,Food,DeliveredStatus,143.59972,171.05913,9.350000,12.650000,89184bb3497ffff,89184bb3497ffff,BICYCLE,43.324664,-1.975841,43.324337,-1.973775,1
1,2023-09-18 10:04:56,Food,DeliveredStatus,1199.57040,1096.33860,14.533333,29.083333,89184bb3413ffff,89184bb3463ffff,BICYCLE,43.319009,-1.983898,43.312050,-1.993499,1
2,2023-09-18 10:16:05,Food,DeliveredStatus,780.57480,1496.59310,25.116667,44.816667,89184bb348fffff,89184bb3463ffff,MOTORBIKE,43.320081,-1.981241,43.309518,-1.992705,1
3,2023-09-18 10:22:29,Food,DeliveredStatus,674.26150,479.59625,13.450000,16.400000,89184bb3413ffff,89184bb3407ffff,BICYCLE,43.319009,-1.983898,43.314906,-1.982061,1
4,2023-09-18 10:49:33,Food,DeliveredStatus,355.18320,1558.99020,31.700000,54.616667,89184bb35cfffff,89184bb3407ffff,MOTORBIKE,43.304142,-1.973532,43.315758,-1.984322,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6494,2023-09-24 23:11:29,Food,DeliveredStatus,473.67685,1487.44710,12.450000,23.683333,89184bb3417ffff,89184bb35cbffff,BICYCLE,43.318830,-1.980115,43.305908,-1.975353,7
6495,2023-09-24 23:11:33,Food,DeliveredStatus,2122.31500,3329.68000,21.616667,56.016667,89184bb26cfffff,89184bb3407ffff,MOTORBIKE,43.309279,-1.943679,43.314300,-1.984250,7
6496,2023-09-24 23:14:07,Food,DeliveredStatus,604.72296,2818.85720,18.350000,31.233333,89184bb3417ffff,89184bb3053ffff,MOTORBIKE,43.318830,-1.980115,43.300658,-2.004410,7
6497,2023-09-24 23:23:59,Food,DeliveredStatus,571.49700,2309.21480,22.783333,34.133333,89184bb3487ffff,89184bb36bbffff,BICYCLE,43.321552,-1.976763,43.316089,-2.004302,7
6498,2023-09-24 23:25:51,Food,DeliveredStatus,41.15646,1125.42430,19.966667,36.050000,89184bb26cfffff,89184949ba3ffff,MOTORBIKE,43.309446,-1.943768,43.319481,-1.945564,7

In [4]:

df = df_food

# Define a dictionary to map old days to new days
day_mapping = {
    1: 7,
    2: 6,
    3: 5,
    4: 4,
    5: 3,
    6: 2,
    7: 1
}


df['day'] = df['day'].map(day_mapping)

In [5]:
df.to_csv('/Users/naroacorettisanchez/Documents/GitHub/DataSS/Deliveries/delivery_demand_ss_flipped_scattered.csv')