In [2]:
#WEEKEND fist
import pandas as pd

df_food= pd.read_csv('/Users/naroacorettisanchez/Documents/GitHub/DataSS/Deliveries/delivery_demand_ss_1week.csv')

In [3]:
df_food

,start_time,order_vertical,order_final_status,start_to_pickup_flight_distance_in_meters,pickup_to_delivery_flight_distance_in_meters,courier_delivery_time_in_minutes,customer_delivery_time_in_minutes,pickup_hexagon_id,delivery_hexagon_id,vehicle_type,start_latitude,start_longitude,end_latitude,end_longitude,day
0,2023-09-18 09:31:39,Food,DeliveredStatus,143.59972,171.05913,9.350000,12.650000,89184bb3497ffff,89184bb3497ffff,BICYCLE,43.324362,-1.974571,43.324362,-1.974571,1
1,2023-09-18 10:04:56,Food,DeliveredStatus,1199.57040,1096.33860,14.533333,29.083333,89184bb3413ffff,89184bb3463ffff,BICYCLE,43.320461,-1.984196,43.311060,-1.992510,1
2,2023-09-18 10:16:05,Food,DeliveredStatus,780.57480,1496.59310,25.116667,44.816667,89184bb348fffff,89184bb3463ffff,MOTORBIKE,43.320922,-1.980084,43.311060,-1.992510,1
3,2023-09-18 10:22:29,Food,DeliveredStatus,674.26150,479.59625,13.450000,16.400000,89184bb3413ffff,89184bb3407ffff,BICYCLE,43.320461,-1.984196,43.314962,-1.982885,1
4,2023-09-18 10:49:33,Food,DeliveredStatus,355.18320,1558.99020,31.700000,54.616667,89184bb35cfffff,89184bb3407ffff,MOTORBIKE,43.304883,-1.972040,43.314962,-1.982885,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6276,2023-09-24 23:11:29,Food,DeliveredStatus,473.67685,1487.44710,12.450000,23.683333,89184bb3417ffff,89184bb35cbffff,BICYCLE,43.317942,-1.981485,43.307403,-1.974751,7
6277,2023-09-24 23:11:33,Food,DeliveredStatus,2122.31500,3329.68000,21.616667,56.016667,89184bb26cfffff,89184bb3407ffff,MOTORBIKE,43.308102,-1.943264,43.314962,-1.982885,7
6278,2023-09-24 23:14:07,Food,DeliveredStatus,604.72296,2818.85720,18.350000,31.233333,89184bb3417ffff,89184bb3053ffff,MOTORBIKE,43.317942,-1.981485,43.301195,-2.004933,7
6279,2023-09-24 23:23:59,Food,DeliveredStatus,571.49700,2309.21480,22.783333,34.133333,89184bb3487ffff,89184bb36bbffff,BICYCLE,43.321382,-1.975972,43.315176,-2.006160,7
6280,2023-09-24 23:25:51,Food,DeliveredStatus,41.15646,1125.42430,19.966667,36.050000,89184bb26cfffff,89184949ba3ffff,MOTORBIKE,43.308102,-1.943264,43.319100,-1.945879,7

In [4]:

df = df_food

# Define a dictionary to map old days to new days
day_mapping = {
    1: 3,
    2: 4,
    3: 5,
    4: 6,
    5: 7,
    6: 1,
    7: 2
}


df['day'] = df['day'].map(day_mapping)

               start_time order_vertical order_final_status  \
0     2023-09-20 09:31:39           Food    DeliveredStatus
1     2023-09-20 10:04:56           Food    DeliveredStatus
2     2023-09-20 10:16:05           Food    DeliveredStatus
3     2023-09-20 10:22:29           Food    DeliveredStatus
4     2023-09-20 10:49:33           Food    DeliveredStatus
...                   ...            ...                ...
6276  2023-09-19 23:11:29           Food    DeliveredStatus
6277  2023-09-19 23:11:33           Food    DeliveredStatus
6278  2023-09-19 23:14:07           Food    DeliveredStatus
6279  2023-09-19 23:23:59           Food    DeliveredStatus
6280  2023-09-19 23:25:51           Food    DeliveredStatus

      start_to_pickup_flight_distance_in_meters  \
0                                     143.59972
1                                    1199.57040
2                                     780.57480
3                                     674.26150
4                                     355.18320
...                                         ...
6276                                  473.67685
6277                                 2122.31500
6278                                  604.72296
6279                                  571.49700
6280                                   41.15646

      pickup_to_delivery_flight_distance_in_meters  \
0                                        171.05913
1                                       1096.33860
2                                       1496.59310
3                                        479.59625
4                                       1558.99020
...                                            ...
6276                                    1487.44710
6277                                    3329.68000
6278                                    2818.85720
6279                                    2309.21480
6280                                    1125.42430

      courier_delivery_time_in_minutes  customer_delivery_time_in_minutes  \
0                             9.350000                          12.650000
1                            14.533333                          29.083333
2                            25.116667                          44.816667
3                            13.450000                          16.400000
4                            31.700000                          54.616667
...                                ...                                ...
6276                         12.450000                          23.683333
6277                         21.616667                          56.016667
6278                         18.350000                          31.233333
6279                         22.783333                          34.133333
6280                         19.966667                          36.050000

     pickup_hexagon_id delivery_hexagon_id vehicle_type  start_latitude  \
0      89184bb3497ffff     89184bb3497ffff      BICYCLE       43.324362
1      89184bb3413ffff     89184bb3463ffff      BICYCLE       43.320461
2      89184bb348fffff     89184bb3463ffff    MOTORBIKE       43.320922
3      89184bb3413ffff     89184bb3407ffff      BICYCLE       43.320461
4      89184bb35cfffff     89184bb3407ffff    MOTORBIKE       43.304883
...                ...                 ...          ...             ...
6276   89184bb3417ffff     89184bb35cbffff      BICYCLE       43.317942
6277   89184bb26cfffff     89184bb3407ffff    MOTORBIKE       43.308102
6278   89184bb3417ffff     89184bb3053ffff    MOTORBIKE       43.317942
6279   89184bb3487ffff     89184bb36bbffff      BICYCLE       43.321382
6280   89184bb26cfffff     89184949ba3ffff    MOTORBIKE       43.308102

      start_longitude  end_latitude  end_longitude
0           -1.974571     43.324362      -1.974571
1           -1.984196     43.311060      -1.992510
2           -1.980084     43.311060      -1.992510
3           -1.984196     43.314962      -1.982885
4           -1.972040     43.314962      -1.982885
...               ...           ...            ...
6276        -1.981485     43.307403      -1.974751
6277        -1.943264     43.314962      -1.982885
6278        -1.981485     43.301195      -2.004933
6279        -1.975972     43.315176      -2.006160
6280        -1.943264     43.319100      -1.945879

[6281 rows x 14 columns]

In [6]:
df.to_csv('/Users/naroacorettisanchez/Documents/GitHub/DataSS/Deliveries/delivery_demand_ss_weekendfirst.csv')